title: Jack Morgan
description: Data Scientist in the Making | Engineering Mathematics at University of Bristol
twitter_username: jack_h_morgan
github_username:  jack-morgan
theme: jekyll-theme-cayman
